### ISSUE TITLE
Is it free to use

### ISSUE THREAD

**Issue by ugintl** [devleaks/print#1]
Is it free to use?

**Comment by devleaks** [comment]
Yes, of course. But there is no migration file added, and no seed data. If you need I can prepare a zip file with it. just give me a few days to prepare it.

**Comment by ugintl** [comment]
@devleaks waiting. When you get back, Also tell me 

1. how to install it?

2. In what context did you developed this app? Did you have specific business type in mind?

**Comment by devleaks** [comment]
Hi.
The repository here can be used as it is. It is a application developed with Yii Framework.
You will not be able to use this application if you don't know Yii framework.
The software is free but I offer no free support. The most I'm willing to do is to send you a dump of a mysql database to get started (with no real data for obvious reasons of confidentiality.) But you need to know how to install a Yii application, how a Yii application works, connects to a database, and so on.
I haven't work on this project for the last few years, I now work on other projects.
Yes, the software is highly specific for a very precise business, however some portion of the software is sufficiently generic to be reused. The software was never designed to be generic, nor to be re-used.
P.
